version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
        
  redis_rest:
    container_name: redis_rest
    image: redis_rest
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6380:6380"